### ISSUE TITLE
Error connecting to the "internet".

### ISSUE THREAD

**Issue by mcm2007** [alfio-event/Alf.ioBackoffice#34]
Hey everyone! Hope than it is all ok. So my problem is this: i have the alf.io instanse deployed on heroku. Everything is "normal" and i was testing the android app to make check in but when i read the QR-Code it says unable to connect to the internet however everything is ok... thanks.

**Comment by PaulGoldschmidt** [comment]
Same problem here, have you found out the root cause of this problem? Seems like a typical firewall error to me, but I found no problem in my configuration.

**Comment by cbellone** [comment]
Hi, please double check the configuration value of "**Base application url**". 
It should not have trailing slashes at the end.

**Comment by PaulGoldschmidt** [comment]
Hey cbellone,

thanks for the hint.
For me, it didn't have the slash at the end, but the protocol (https://) specified in the front; For testing purposes, I tried to delete the protocol in the front of the url, but with no luck. I tried decoding the QR-Code generated in Alf.io and it looks like it kept the old version of the URL in the generation of the QR-Code (it includes the https://). Restarting the container, clearing the cache did not change that behaviour.
Does the app connect to any ports other than 443 for TCP/https?

Kind regards and thanks a lot,
Paul

**Comment by cbellone** [comment]
> For me, it didn't have the slash at the end, but the protocol (https://) specified in the front; For testing purposes, I tried to delete the protocol in the front of the url, but with no luck. I tried decoding the QR-Code generated in Alf.io and it looks like it kept the old version of the URL in the generation of the QR-Code (it includes the https://)

OK, thanks for testing. My suggestion was actually wrong. 
As you can see [here](https://github.com/alfio-event/alf.io/blob/master/src/main/webapp/resources/js/admin/feature/users/users.js#L110) the QR code will always include the origin of the page where you generate it. In your case, `https://your-domain.tld`.
We should probably change this...

Anyway, what happens if you execute the following GET?

`curl -vvv -H 'Authorization: ApiKey ApiKeyFromQrCode' https://your-domain.tld/admin/api/user/details`

Please replace:
- ApiKeyFromQrCode with the actual ApiKey
- your-domain.tld with the actual server domain

**Comment by PaulGoldschmidt** [comment]
Alright, very interesting indeed; I'm starting to think that Cloudflare as the CDN is a possible origin of this problem, but Cloudflare _should_ forward all HTTP request headers (see [Cloudflare Docs](https://developers.cloudflare.com/fundamentals/get-started/http-request-headers/)).
The output of cURL (with the URL, Domain and some other privacy related stuff) can be found here:
https://gist.github.com/PaulGoldschmidt/ed60124ec848c04ab16b303001248667

Thanks again for the help,
Paul

**Comment by PaulGoldschmidt** [comment]
Hey @cbellone, I worked in the backgrund a litte further on the problem - are you sure, that this issue is not affecting everyone? I have the same exact problem with the demo instance of Alf.io, so I also get the "Internet error" message after creating an Check-In user.
Could you confirm that this Issue I'm experiencing is isolated and thus the app works for you?

Kind regards,
Paul

**Comment by PaulGoldschmidt** [comment]
Hey @mcm2007,

have you figured out a way to fix this issue?

All the best,
Paul

**Comment by cbellone** [comment]
Hi,
I've just tested with the demo instance (demo.alf.io). 
I've created a new account, a new event and generated an API Key. Everything works as expected. I have an android 12 phone.

Can you please do the following:

1. Please double check the process of generating the API Key on the [how to guide](https://alf.io/docs/event-management/check-in/check-in-app/)
2. Let me know step by step how can I reproduce it

thank you!

**Comment by PaulGoldschmidt** [comment]
Hey,

thanks for the Reply. I did some testing today and figured out the issue: Cloudflare blocked some requests regarding the mobile communication (maybe connected to their Brotli-Compression?), turning higher levels of cashing has illuminated the issue. 

Thank you so much for your help!
Kind regards,
Paul
